import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../component/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
         <Navbar/>
         <div className={styles.container}>
          <div className={styles.overlay}>
                <div className={styles.main}>
                  <h1>Your one stop shop for vehicle care</h1>
                  <h2>High quality, convenient and sustainable car care, all through one app</h2>
                  <h4>Mobile Body Repair - Mobile Valet - Mobile Mechanics</h4>
                  <button>Book now</button>
                </div>

          </div>
         </div>
     
    </div>
  )
}
